export const state = {
  setlist:      [],
  fileId:       null,
  token:        null,
  tokenExpiry:  0,
  currentTab:   'upcoming',
  typeFilters:  { upcoming: 'all', attended: 'all' },
  query:        '',
  saveTimer:    null,
  modalType:    'show',
  modalStatus:  'interested',
  storedCity:   '',
  storedCountry: '',
  PlacesLib:    null,
  placesToken:  null,
  mbTimer:      null,
  venueTimer:   null,
  tokenClient:  null,
  editId:       null,
  editLineup:   [],
};
